name: patient
description: flutter patient app

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  #https://github.com/flutterchina/dio
  # url_launcher: 4.0.1
  #https://github.com/flutterchina/dio
  dio: ^3.0.9
  #https://pub.flutter-io.cn/packages/provider
  provider: ^4.0.4
  # https://github.com/theyakka/fluro
  fluro: "^1.6.1"
  #https://pub.flutter-io.cn/packages/shared_preferences#-readme-tab-
  shared_preferences: ^0.5.6+3
  # https://github.com/flutterchina/dio/tree/master/plugins/cookie_manager
  dio_cookie_manager: 1.0.0
  # https://github.com/flutterchina/cookie_jar
  cookie_jar: ^1.0.0
  # https://pub.flutter-io.cn/packages/path_provider
  path_provider: ^1.6.5
  # https://github.com/tekartik/synchronized.dart
  synchronized: ">=1.5.1 <3.0.0"
  # https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^2.0.0-rc
  # https://flui.xin/guide.html     ui
  flui: 0.9.0
  # https://docs.getflutter.dev  另一个ui，打开太慢了
  # https://github.com/OpenFlutter/flutter_screenutil
  flutter_screenutil: ^1.0.2
  # https://pub.flutter-io.cn/packages/decimal
  decimal: ^0.3.5
  # https://s0pub0dev.icopy.site/packages/dotted_border 虚线边框
#  dotted_border: ^1.0.5
  # https://github.com/SunPointed/MPFlutterChart
  mp_chart: ^0.1.9
  # https://pub.flutter-io.cn/packages/fl_chart 比较平滑
  fl_chart:
    #    ^0.9.2
    path: plugins/fl_chart  # 本地修改了折线图，在点上显示数值。
  # https://pub.flutter-io.cn/packages/fl_chart#-example-tab-  另一个图表库
  # charts_flutter: ^0.9.0
  json_annotation     : ^3.0.0
  #https://pub.dev/packages/sqflite 数据库
  sqflite: ^1.3.0
  #https://pub.dev/packages/path  // 提供了大量方法，以便你能正确的定义数据库在磁盘上的存储位置。
  path: ^1.6.4
  #https://pub.dev/packages/sprintf //  format an interploated String
  sprintf: ^4.0.2
  # https://pub.dev/packages/json_annotation   Provides source_gen Generators to create code for JSON serialization and deserialization.
  #网易云IM
  nim:
    path: plugins/nim
  flutter_picker: ^1.1.0
  date_format: ^1.0.8  #时间处理
#  barcode_scan: any

dev_dependencies:
  # https://pub.flutter-io.cn/packages/pedantic 代码风格检查
  pedantic: ^1.8.0
  effective_dart: ^1.0.0
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  mockito: ^4.1.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/medic/plan/
    - assets/images/health/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
